import { QuizData, QuizQuestion } from '../types';

export interface QuizPreset {
  label: string;
  topic: string;
  subject: string;
  difficulty: 'Easy' | 'Intermediate' | 'Hard';
  notes: string;
}

export const QUIZ_PRESETS: QuizPreset[] = [
  {
    label: 'Trees & Self-Balancing BSTs',
    topic: 'Binary Search Trees, AVL Trees, and Red-Black Properties',
    subject: 'Data Structures & Algorithms',
    difficulty: 'Intermediate',
    notes: 'Focus on insertion rotations (LL, RR, LR, RL), height balance factor in AVL trees, Red-Black color invariants, and search time complexity O(log N).'
  },
  {
    label: 'OS Deadlocks & Synchronization',
    topic: 'Deadlock Necessary Conditions, Banker\'s Algorithm & Semaphores',
    subject: 'Operating Systems',
    difficulty: 'Intermediate',
    notes: 'Cover Coffman\'s four conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait. Safe states vs unsafe states, and resource allocation graphs.'
  },
  {
    label: 'SQL Indexing & ACID Transactions',
    topic: 'B-Tree Indexing, Query Optimization, and ACID Properties',
    subject: 'Database Systems',
    difficulty: 'Hard',
    notes: 'Examine Atomicity, Consistency, Isolation levels (Dirty Read, Non-repeatable read, Phantom read), Durability via WAL logs, and composite index column order.'
  },
  {
    label: 'Cellular Respiration & Krebs Cycle',
    topic: 'Glycolysis, Krebs Cycle, and Electron Transport Chain',
    subject: 'Biochemistry & Life Sciences',
    difficulty: 'Intermediate',
    notes: 'ATP yield calculations, substrate-level vs oxidative phosphorylation, NADH/FADH2 electron carriers, and chemiosmosis across inner mitochondrial membrane.'
  },
  {
    label: 'Quantum Superposition & Gates',
    topic: 'Bloch Sphere, Hadamard Gates, and Quantum Entanglement',
    subject: 'Quantum Physics',
    difficulty: 'Hard',
    notes: 'Qubit state vectors, superposition principles, unitary quantum logic gates (Hadamard, CNOT, Pauli-X), Bell states, and quantum measurement collapse.'
  }
];

/**
 * Generates a clean, formatted Markdown document for testing or printing
 */
export function exportQuizToMarkdown(quiz: QuizData, includeAnswers = true): string {
  const lines: string[] = [];
  lines.push(`# Exam / Quiz: ${quiz.topic}`);
  lines.push(`*Total Questions: ${quiz.questions.length} | Date Generated: ${new Date().toLocaleDateString()}*\n`);
  lines.push('---\n');

  quiz.questions.forEach((q, idx) => {
    lines.push(`### Question ${idx + 1}`);
    lines.push(`${q.question}\n`);
    q.options.forEach((opt, oIdx) => {
      lines.push(`- **${String.fromCharCode(65 + oIdx)}.** ${opt}`);
    });
    lines.push('');
  });

  if (includeAnswers) {
    lines.push('\n---\n');
    lines.push('## 📝 Answer Key & Explanations\n');
    quiz.questions.forEach((q, idx) => {
      const correctLetter = String.fromCharCode(65 + q.correctAnswer);
      lines.push(`**Q${idx + 1}:** ${correctLetter} - *${q.options[q.correctAnswer]}*`);
      lines.push(`> **Explanation:** ${q.explanation}\n`);
    });
  }

  return lines.join('\n');
}

/**
 * Creates an offline-ready printable HTML test paper
 */
export function generatePrintableHtmlQuiz(quiz: QuizData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Quiz: ${quiz.topic}</title>
<style>
  body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: auto; }
  h1 { border-bottom: 2px solid #0f172a; padding-bottom: 8px; font-size: 24px; }
  .meta { color: #64748b; font-size: 14px; margin-bottom: 30px; }
  .q-card { margin-bottom: 24px; padding: 16px; border: 1px solid #e2e8f0; border-radius: 8px; page-break-inside: avoid; }
  .q-title { font-weight: 700; margin-bottom: 12px; font-size: 15px; }
  .option { margin-bottom: 6px; font-size: 14px; padding-left: 10px; }
  .answer-key { margin-top: 40px; border-top: 2px dashed #94a3b8; padding-top: 20px; page-break-before: always; }
  .exp { background: #f8fafc; padding: 8px 12px; border-left: 3px solid #2DD4BF; font-size: 13px; color: #475569; margin-top: 6px; }
  @media print {
    body { padding: 0; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 20px;">
    <button onclick="window.print()" style="padding: 10px 20px; background: #2563eb; color: #fff; border: none; border-radius: 6px; font-weight: bold; cursor: pointer;">
      🖨️ Print Exam Paper (PDF)
    </button>
  </div>

  <h1>${quiz.topic}</h1>
  <div class="meta">Total Questions: ${quiz.questions.length} &bull; Generated by Lumora AI Quiz Generator</div>

  ${quiz.questions.map((q, idx) => `
    <div class="q-card">
      <div class="q-title">Q${idx + 1}. ${q.question}</div>
      ${q.options.map((opt, oIdx) => `
        <div class="option"><strong>${String.fromCharCode(65 + oIdx)}.</strong> ${opt}</div>
      `).join('')}
    </div>
  `).join('')}

  <div class="answer-key">
    <h2>Answer Key & Solutions</h2>
    ${quiz.questions.map((q, idx) => `
      <div style="margin-bottom: 16px;">
        <strong>Q${idx + 1}: ${String.fromCharCode(65 + q.correctAnswer)}</strong> (${q.options[q.correctAnswer]})
        <div class="exp">💡 ${q.explanation}</div>
      </div>
    `).join('')}
  </div>
</body>
</html>`;
}

/**
 * Format seconds to MM:SS
 */
export function formatQuizTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}
